code --install-extension bierner.markdown-mermaid
code --install-extension bradlc.vscode-tailwindcss
code --install-extension digitalbrainstem.javascript-ejs-support
code --install-extension editorconfig.editorconfig
code --install-extension esbenp.prettier-vscode
code --install-extension fabiospampinato.vscode-monokai-night
code --install-extension github.github-vscode-theme
code --install-extension golang.go
code --install-extension hashicorp.terraform
code --install-extension humao.rest-client
code --install-extension j69.ejs-beautify
code --install-extension jeffersonlicet.snipped
code --install-extension mhutchie.git-graph
code --install-extension mikestead.dotenv
code --install-extension mongodb.mongodb-vscode
code --install-extension ms-azuretools.vscode-containers
code --install-extension ms-azuretools.vscode-docker
code --install-extension raidou.calc
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-russian
code --install-extension wmaurer.change-case
